server:
  port: 9898
spring:
  profiles:
    active: ${PRODILE:prod}
  config:
    import: optional:configserver:${CONFIG_SERVER_URL:http://127.0.0.1:9997}
  cloud:
    config:
      label: ${CONFIG_BRANCH:master}
      username: ${SERVER_USER:isaev}
      password: ${SERVER_PASS:isaev_pass}
